# Generated by Django 5.1.5 on 2025-02-05 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0005_fileupload_alter_profile_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tel',
            field=models.IntegerField(default=123456789, max_length=100),
        ),
    ]
