# Generated by Django 5.1.5 on 2025-02-05 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0006_alter_profile_tel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tel',
            field=models.IntegerField(default=123456789),
        ),
    ]
